
server:
  port: 8080

ocr:
  url: http://192.168.26.124:10008

logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.leepon.cloud: DEBUG