spring:
  application:
    name: microservice-zuul
server:
  port: 8080
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

zuul:
  ignoredServices: "*"
  routes:
    MICROSERVICE-PRODUCT: /v1/product/**
    MICROSERVICE-USER : /v1/user/**

microservice-user:
  ribbon:
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    listOfServers: http://localhost:7900,http://localhost:7901


logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.leepon.cloud: DEBUG