spring:
  application:
    name: microservice-retry

logging:
  level:
    com.leepon.cloud.outer.IOuterUserService: DEBUG

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true


hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000